export enum SupportTicketStatus {
  OPEN = 'OPEN',
  IN_ANALYSIS = 'IN_ANALYSIS',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  WAITING_INTERNAL = 'WAITING_INTERNAL',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}
